version: "3.8"

networks:
  externa:

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: Jenkins
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./${myname}/jenkins_compose/jenkins_conf:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - externa

